data = {"quizcontent": [
  {
    "question": "What's the name of the mysterious blue glowing cube that Loki uses as a weapon?", 
    "image": "assets/image-1.jpeg",
    "answer": "2",
    "a1": "Flux Capacitor",
    "a2": "Tesseract",
    "a3": "The Force",
    "a4": "Mother Cube",
  },
  {
    "question": "Which movie did Black Widow appear first in the MCU?", 
    "image": "assets/image-2.jpeg",
    "answer": "2",
    "a1": "Avengers",
    "a2": "Iron Man 2",
    "a3": "Captain America: Civil War",
    "a4": "Black Widow",
  },
  {
    "question": "What is the name of Thor’s hammer? ", 
    "image": "assets/image-3.jpeg",
    "answer": "3",
    "a1": "Stormbreaker",
    "a2": "Mighty Hammer",
    "a3": "Mjölnir",
    "a4": "Jonathan",
  },
  {
    "question": "Which superhero does Bruce Banner transform into?", 
    "image": "assets/image-4.jpeg",
    "answer": "4",
    "a1": "Iron Man",
    "a2": "Hawkeye",
    "a3": "Thor",
    "a4": "The Hulk",
  },
  {
    "question": "Before becoming Vision, what was the name of Iron Man’s A.I. butler?", 
    "image": "assets/image-5.jpeg",
    "answer": "2",
    "a1": "H.O.M.E.R.",
    "a2": "J.A.R.V.I.S.",
    "a3": "A.L.F.R.E.D.",
    "a4": "M.A.R.V.I.N",
  },
]}